"""Regenerates the Expert Sierra table config from Unity Catalog: the Raw inventory and the Bronze table list.

Run it when Raw tables are added or removed:

    DATABRICKS_CONFIG_PROFILE=<profile> uv run python use_cases/expert_sierra/generate_config.py \
        --catalog expertsierra_dev [--row-counts --warehouse-id <id>]

Writes, relative to this folder:
    config/raw_inventory.csv    one row per Raw table: primary key, column counts (and row counts)
    config/bronze_tables.yml    the tables to load into Bronze, each with `enabled` and `load_mode`.
                                Existing entries keep their settings; new Raw tables are added as
                                enabled with `full`; tables no longer in Raw are removed.
"""
import argparse
import csv
import json
from pathlib import Path

import yaml
from databricks.sdk import WorkspaceClient

CONFIG_DIR = Path(__file__).resolve().parent / "config"
TABLES_FILE = CONFIG_DIR / "bronze_tables.yml"
RAW_SCHEMA = "dbo_raw"
PRIMARY_KEY_PROPERTY = "__ingestion_connector_primary_key"
LOAD_MODES = ("full", "incremental")
DEFAULT_LOAD_MODE = "full"

TABLES_HEADER = """\
# Expert Sierra tables to load from Raw into Bronze, used by use_cases/expert_sierra/bronze_load.ipynb.
# Generated by use_cases/expert_sierra/generate_config.py; edit the settings freely, re-running keeps them.
#   enabled:    false skips the table
#   load_mode:  full         overwrite Bronze from the Raw snapshot (while Raw is truncated and reloaded)
#               incremental  append new and updated Raw rows from the change feed
"""


def row_counts(client: WorkspaceClient, warehouse_id: str, catalog: str, tables: list) -> dict:
    """Counts rows in every Raw table with one SQL statement."""
    query = " UNION ALL ".join(
        f"SELECT '{t}' AS t, COUNT(*) AS n FROM `{catalog}`.`{RAW_SCHEMA}`.`{t}`" for t in tables
    )
    result = client.statement_execution.execute_statement(
        statement=query, warehouse_id=warehouse_id, wait_timeout="50s"
    )
    while result.status.state.value in ("PENDING", "RUNNING"):
        result = client.statement_execution.get_statement(result.statement_id)
    if result.status.state.value != "SUCCEEDED":
        raise RuntimeError(f"Row count query failed: {result.status.error}")
    return {name: int(count) for name, count in result.result.data_array}


def write_inventory(tables: list, counts: dict) -> None:
    with open(CONFIG_DIR / "raw_inventory.csv", "w", newline="") as inventory:
        writer = csv.writer(inventory)
        writer.writerow(["source_table", "primary_key", "column_count", "char_columns", "string_columns", "row_count"])
        for table in tables:
            columns = table.columns or []
            primary_key = json.loads((table.properties or {}).get(PRIMARY_KEY_PROPERTY, "[]"))
            type_names = [column.type_name.value for column in columns]
            writer.writerow([
                table.name, ";".join(primary_key), len(columns),
                type_names.count("CHAR"), type_names.count("STRING"), counts.get(table.name, ""),
            ])


def write_tables(table_names: list) -> None:
    """Writes the Bronze table list, keeping the settings of tables already in it."""
    existing = {}
    if TABLES_FILE.exists():
        existing = {t["name"]: t for t in (yaml.safe_load(TABLES_FILE.read_text()) or {}).get("tables", [])}

    entries = []
    for name in table_names:
        current = existing.get(name, {})
        entries.append({
            "name": name,
            "enabled": current.get("enabled", True),
            "load_mode": current.get("load_mode", DEFAULT_LOAD_MODE),
        })
    TABLES_FILE.write_text(TABLES_HEADER + yaml.safe_dump({"tables": entries}, sort_keys=False))

    added = sorted(set(table_names) - existing.keys())
    removed = sorted(existing.keys() - set(table_names))
    if existing and added:
        print(f"Added to bronze_tables.yml: {', '.join(added)}")
    if removed:
        print(f"Removed from bronze_tables.yml (no longer in Raw): {', '.join(removed)}")


def main(argv=None) -> None:
    parser = argparse.ArgumentParser(description="Regenerate the Expert Sierra inventory and Bronze table list")
    parser.add_argument("--catalog", required=True, help="catalog holding the Raw schema, e.g. expertsierra_dev")
    parser.add_argument("--row-counts", action="store_true", help="also count rows (needs --warehouse-id)")
    parser.add_argument("--warehouse-id", help="SQL warehouse for --row-counts")
    args = parser.parse_args(argv)

    client = WorkspaceClient()
    tables = sorted(client.tables.list(args.catalog, RAW_SCHEMA), key=lambda t: t.name)
    counts = row_counts(client, args.warehouse_id, args.catalog, [t.name for t in tables]) if args.row_counts else {}

    write_inventory(tables, counts)
    write_tables([t.name for t in tables])
    print(f"Wrote {len(tables)} tables to {CONFIG_DIR / 'raw_inventory.csv'} and {TABLES_FILE}")


if __name__ == "__main__":
    main()
